# Codecov configuration for SpiceLab
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "**/__init__.py"
  - "**/conftest.py"

flags:
  unittests:
    paths:
      - spicelab/
    carryforward: true
