site_name: spicelab
site_description: Unified Python orchestration for SPICE simulations
site_author: lgili
repo_name: lgili/spicelab
site_url: https://lgili.github.io/CircuitToolkit/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            # Extra options must be nested under `extra` to avoid deprecation
            # warnings. `search_path` tells the python handler where to look
            # for the local package in a root-layout project.
            extra:
              search_path:
                - .

nav:
  - Overview:
    - Welcome: index.md
    - Installation: installation.md
    - Getting started: getting-started.md
    - Concepts: concepts.md
  - User guide:
    - Engines: engines.md
    - Data I/O: unified-io.md
    - Sweeps & grids: sweeps-step.md
    - Monte Carlo: monte-carlo.md
    - Reporting: reporting.md
    - Plotting: plots.md
    - Circuit preview: preview.md
    - LTspice integration: ltspice-import.md
    - Analog mux: mux-enable-ports.md
    - CLI & CI automation: cli-ci.md
    - Environment doctor: doctor.md
    - Troubleshooting: troubleshooting.md
  - Components:
    - Overview: components.md
    - Quick reference: components-quickstart.md
    - Device models: device-models.md
    - Library status (refresh soon): components-library.md
  - Examples:
    - Overview: examples.md
    - Running scripts: examples-usage.md
    - Gallery: examples-gallery.md
    - Monte Carlo assets: monte-carlo-example.md
    - Notebooks: notebooks.md
  - Cookbook: cookbook.md
  - Reference:
    - API guidance: api-reference.md
    - Core API: reference/core.md
    - IO API: reference/io.md
    - Analysis API: reference/analysis.md
  - Legacy & roadmap:
    - AC stability (refresh soon): ac-stability.md
    - Op-amp stability (refresh soon): opamp-stability.md
    - Old roadmap (M1/M2): core-contracts.md
  - Changelog:
    - M6 Wrap-up: changelog-m6.md
extra_css:
  - assets/stylesheets/extra.css
extra: {}
