"""Public analysis helpers for the unified API."""

from __future__ import annotations

from .measure import (
    ENOBSpec,
    GainBandwidthSpec,
    GainMarginSpec,
    GainSpec,
    OvershootSpec,
    PhaseMarginSpec,
    RiseTimeSpec,
    SettlingTimeSpec,
    SlewRateSpec,
    THDSpec,
    measure,
)
from .montecarlo import (
    CorrelatedGroup,
    Dist,
    LogNormalPct,
    MonteCarloResult,
    NormalAbs,
    NormalPct,
    TriangularAbs,
    TriangularPct,
    UniformAbs,
    UniformPct,
    monte_carlo,
)
from .optimized import (
    OptimizationConfig,
    OptimizationStats,
    OptimizedMonteCarlo,
    OptimizedWCA,
    create_monte_carlo_runner,
    create_wca_runner,
    quick_monte_carlo,
    quick_wca,
)
from .pipeline import measure_job_result, run_and_measure
from .report import (
    ReportConfig,
    ReportSection,
    generate_monte_carlo_report,
    generate_report,
    generate_wca_report,
)
from .result import AnalysisResult
from .sensitivity_extended import (
    ComponentTolerance,
    DesignMargin,
    DesignMarginResult,
    SensitivityReport,
    SensitivityReportSection,
    TemperaturePoint,
    TemperatureSensitivityResult,
    ToleranceImpact,
    ToleranceSensitivityResult,
    analyze_design_margins,
    create_sensitivity_report,
    temperature_sensitivity,
    tolerance_sensitivity,
)
from .signal import FFTResult, amplitude_spectrum, power_spectral_density, rfft_coherent, window
from .stats import (
    Statistics,
    compute_stats,
    create_metric_extractor,
    extract_from_analysis,
    extract_trace_value,
    get_current,
    get_power,
    get_voltage,
    mc_summary,
    sigma_level,
)
from .sweep import (
    ConditionResult,
    MonteCarloConditionResult,
    MonteCarloSweepResult,
    WcaConditionResult,
    WcaSweepResult,
    monte_carlo_sweep,
    wca_sweep,
)
from .sweep_grid import (
    GridResult,
    GridRun,
    SweepResult,
    SweepRun,
    run_param_grid,
    run_value_sweep,
)
from .wca import (
    ToleranceSpec,
    WcaCorner,
    WcaResult,
    run_wca,
    tolerance_to_normal,
    tolerance_to_uniform,
)

__all__ = [
    "AnalysisResult",
    "measure",
    "GainSpec",
    "PhaseMarginSpec",
    "GainBandwidthSpec",
    "GainMarginSpec",
    "OvershootSpec",
    "RiseTimeSpec",
    "SettlingTimeSpec",
    "THDSpec",
    "ENOBSpec",
    "SlewRateSpec",
    "CorrelatedGroup",
    "Dist",
    "NormalAbs",
    "NormalPct",
    "TriangularAbs",
    "TriangularPct",
    "UniformAbs",
    "UniformPct",
    "LogNormalPct",
    "MonteCarloResult",
    "monte_carlo",
    "SweepRun",
    "SweepResult",
    "GridRun",
    "GridResult",
    "run_value_sweep",
    "run_param_grid",
    "window",
    "rfft_coherent",
    "amplitude_spectrum",
    "power_spectral_density",
    "FFTResult",
    "measure_job_result",
    "run_and_measure",
    # WCA
    "ToleranceSpec",
    "WcaCorner",
    "WcaResult",
    "run_wca",
    "tolerance_to_normal",
    "tolerance_to_uniform",
    # Statistics
    "Statistics",
    "compute_stats",
    "extract_trace_value",
    "extract_from_analysis",
    "mc_summary",
    "create_metric_extractor",
    "get_voltage",
    "get_current",
    "get_power",
    "sigma_level",
    # Optimized runners
    "OptimizationConfig",
    "OptimizationStats",
    "OptimizedMonteCarlo",
    "OptimizedWCA",
    "quick_monte_carlo",
    "quick_wca",
    "create_monte_carlo_runner",
    "create_wca_runner",
    # Extended sensitivity analysis (M16)
    "temperature_sensitivity",
    "tolerance_sensitivity",
    "TemperaturePoint",
    "TemperatureSensitivityResult",
    "ComponentTolerance",
    "ToleranceImpact",
    "ToleranceSensitivityResult",
    "SensitivityReport",
    "SensitivityReportSection",
    "create_sensitivity_report",
    "DesignMargin",
    "DesignMarginResult",
    "analyze_design_margins",
    # Condition sweep
    "ConditionResult",
    "MonteCarloConditionResult",
    "MonteCarloSweepResult",
    "WcaConditionResult",
    "WcaSweepResult",
    "monte_carlo_sweep",
    "wca_sweep",
    # Report generation
    "ReportConfig",
    "ReportSection",
    "generate_monte_carlo_report",
    "generate_report",
    "generate_wca_report",
]
