from __future__ import annotations

# Public API for spicelab.core subpackage. Keep minimal and explicit to satisfy
# linters and to make the package importable by tools like griffe/mkdocstrings.
from .circuit import Circuit
from .components import (
    JFET,
    BCurrent,
    BVoltage,
    Capacitor,
    CurrentProbe,
    Inductor,
    Ipulse,
    Ipwl,
    MutualInductance,
    OpAmpIdeal,
    Resistor,
    SubcktInstance,
    TLine,
    TLineLossy,
    TLineRC,
    Transformer,
    VCCSExpr,
    VCVSExpr,
    Vdc,
    VoltageProbe,
    Vpulse,
    Vpwl,
    ZenerDiode,
)
from .net import GND, Net
from .subcircuit import (
    SubcircuitDefinition,
    SubcircuitLibrary,
    SubcircuitParameter,
    SubcircuitPort,
    get_subcircuit,
    get_subcircuit_library,
    register_subcircuit,
)

__all__ = [
    "BCurrent",
    "BVoltage",
    "Capacitor",
    "Circuit",
    "CurrentProbe",
    "GND",
    "Inductor",
    "Ipulse",
    "Ipwl",
    "JFET",
    "MutualInductance",
    "Net",
    "OpAmpIdeal",
    "Resistor",
    "SubcktInstance",
    "TLine",
    "TLineLossy",
    "TLineRC",
    "Transformer",
    "VCCSExpr",
    "VCVSExpr",
    "Vdc",
    "VoltageProbe",
    "Vpulse",
    "Vpwl",
    "ZenerDiode",
    # Subcircuit support (M8)
    "SubcircuitDefinition",
    "SubcircuitLibrary",
    "SubcircuitParameter",
    "SubcircuitPort",
    "get_subcircuit",
    "get_subcircuit_library",
    "register_subcircuit",
]
