# src/cat/__init__.py

# Top-level convenient API imports

# Core building blocks
# Analyses and utilities
from .analysis import (
    AC,
    DC,
    OP,
    TRAN,
    AnalysisResult,
    Dist,
    LogNormalPct,
    MonteCarloResult,
    NormalPct,
    ParamGrid,
    StepNativeResult,
    StepResult,
    SweepResult,
    TriangularPct,
    UniformAbs,
    UniformPct,
    WorstCaseResult,
    ac_gain_phase,
    bandwidth_3db,
    crossover_freq_0db,
    gain_db_from_traces,
    gain_margin_db,
    monte_carlo,
    overshoot_pct,
    peak,
    phase_crossover_freq,
    phase_margin,
    run_step_native,
    settling_time,
    stack_runs_to_df,
    stack_step_to_df,
    step_grid,
    step_param,
    sweep_component,
    worst_case,
)

# Plotting
from .analysis.viz.plot import (
    plot_bode,
    plot_sweep_df,
    plot_traces,
)
from .core.circuit import Circuit
from .core.components import (
    IA,
    VA,
    C,
    Capacitor,
    I,
    Iac,
    Idc,
    Inductor,
    L,
    R,
    Resistor,
    V,
    Vdc,
)
from .core.net import GND, Net

__all__ = [
    # Core
    "Circuit",
    "Net",
    "GND",
    "Resistor",
    "Capacitor",
    "Inductor",
    "Vdc",
    "VA",
    "R",
    "C",
    "V",
    "L",
    "Idc",
    "Iac",
    "I",
    "IA",
    # Analyses
    "OP",
    "TRAN",
    "AC",
    "DC",
    "AnalysisResult",
    # Sweeps/Steps
    "SweepResult",
    "sweep_component",
    "ParamGrid",
    "StepResult",
    "step_param",
    "step_grid",
    "stack_step_to_df",
    "stack_runs_to_df",
    # Metrics
    "peak",
    "settling_time",
    "overshoot_pct",
    "gain_db_from_traces",
    "bandwidth_3db",
    "ac_gain_phase",
    "crossover_freq_0db",
    "phase_margin",
    "phase_crossover_freq",
    "gain_margin_db",
    # Monte Carlo / Worst case
    "Dist",
    "NormalPct",
    "UniformPct",
    "LogNormalPct",
    "TriangularPct",
    "UniformAbs",
    "MonteCarloResult",
    "monte_carlo",
    "WorstCaseResult",
    "worst_case",
    "StepNativeResult",
    "run_step_native",
    # Plotting
    "plot_traces",
    "plot_bode",
    "plot_sweep_df",
]
